# Generated by Django 6.0.4 on 2026-05-05 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.IntegerField(default=0)),
                ('total_grade_points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gp', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('degree_class', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('credit_unit', models.IntegerField()),
                ('score', models.IntegerField()),
                ('grade_point', models.IntegerField(default=0)),
                ('grade_letter', models.CharField(default='F', max_length=2)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='calculator.result')),
            ],
        ),
    ]
